# Carlos Ramirez - Personal Landing Page
title: Carlos Ramirez
author: Carlos Leonel Ramirez
description: IT Professional | Cloud & DevOps | AWS

# URLs
url: "https://carloslramirez.com"
baseurl: ""

# Build settings
markdown: kramdown
timezone: "America/Guatemala"

# Exclude files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - beautiful-jekyll-theme.gemspec
